###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
default_redirection_url: https://login.nelands.me
totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: one_factor
  rules:
    # Rules applied to everyone
    - domain: searcher.nelands.me
      policy: one_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # secret: unsecure_session_secret
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: nelands.me # Should match whatever your root protected domain is

  redis:
    host: authelia_redis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  postgres:
    host: authelia_db
    port: 5432
    database: authelia
    username: authelia
    # This can be set using env variables AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
    # password: mypassword
    sslmode: disable

notifier:
  smtp:
    username: thomas.falcone06@gmail.com
    # Password can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
    # password: yourapppassword
    sender: admin@nelands.me
    host: smtp.gmail.com
    port: 587
